### PR TITLE
Reorganize repository into a Vagrant plugin

### PR DESCRIPTION
**Pull request by kiall**

### CODE REVIEW

**Comment by kiall** [comment]
I've moved the readme and example files into an example folder, I assume the top level readme (if this PR is merged..) should be updated to suit usage as a plugin..

**Comment by akoumjian** [comment]
Hey, this is great! 

I agree regarding the README and example. Since I am not really a Ruby/Vagrant dev, would you mind updating the documentation to explain its usage as a plugin (for my benefit as well)?

After that I will give it a whirl. 

Again, thank you!

**Comment by akoumjian** [comment]
Also, I did not want to call it vagrant-salt as there was another project with that name when I wrote it.

**Comment by akoumjian** [comment]
Also, add yourself to the authors list.

**Comment by kiall** [comment]
Re the gem name - I just went with convention for vagrant plugins - and it hasn't been nabbed on rubygems.org yet ;) 

The only vagrant-salt github repo's I know have very different purposes, are are not actually Vagrant plugins..

Re the docs - Sure.. But - it won't be today!

**Comment by kiall** [comment]
So.. I lied. The readme updates were minimal. That should be good to go..

Obviously, for `gem install vagrant-salt` to work, you would need to do a release to rubygems.. Since your not a ruby dev:
1. Register at rubygems.org
2. `mkdir ~/.gem`
3. `curl -u $USERNAME https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials`
4. `rake release`

(Sometimes I've noticed issues with `rake release`, if it fails, try `gem push pkg/vagrant-salt-0.1.gem`)

**Comment by akoumjian** [comment]
You, sir, are a gentleman and a scholar. I will set this up now.

**Comment by akoumjian** [comment]
It appears to work. I have just installed the gem from ruby gems and successfully provisioned a machine with it. 

One question: how would I install the gem from a local directory while developing the provisioner?

For example, with python development you can use `python setup.py develop` which links the current working directory with the module in the site-packages directory.

**Comment by kiall** [comment]
Two options - the example/Vagrantfile makes use of the local stuff by just requiring it explicitly..

or you could use something like `RUBYLIB=./lib vagrant up`

**Comment by akoumjian** [comment]
Is there something that ruby developers do when they want the project they are working on to be in the system namespace (ie: available via `require mylib`) but keep the project files in their regular project directory?

With python, when you pip install -e mylib or python setup.py develop it essentially symlinks the working project directory.

**Pull request merged**
