### PR TITLE
copy minion conf to /etc/salt/minion if specifed in Vagrantfile

### PR DESCRIPTION
**Pull request by timoguin**
Hopefully this fixes the bug! It works for me at least.

### CODE REVIEW

**Comment by akoumjian** [comment]
Thanks @timoguin. However, I'm in the middle of a big update which will fix along with updating options for latest bootstrap. Should be out soon. It's appreciated, though! I'll keep this open until I push the update.

**Comment by subru77** [comment]
I had the same problem. The minion.conf was not getting copied over. When would you think this would be resolved ? Or can I apply this patch ?

**Comment by akoumjian** [comment]
I'm almost done with the next release, but work keeps me very busy. I would recommend continuing to use your patch until the next release (hopefully next day or two).

**Comment by subru77** [comment]
Thanks  Alec

**Comment by timoguin** [comment]
Yes, thanks.

**Pull request closed without merging**
