### PR TITLE
Update salt-bootstrap script to HEAD.

### PR DESCRIPTION
**Pull request by alecthomas**
Fixes outdated EPEL issue.

Currently, salty-vagrant fails to install with:

```
[default]  * INFO: Found function install_centos_63_stable_post
 * Running install_centos_63_stable_deps()
[default] c
[default] u
[default] r
[default] l
[default] :
[default]
[default] (
[default] 2
[default] 2
[default] )
[default]
[default] T
[default] he requested URL returned error: 404
error: skipping http://mirrors.kernel.org/fedora-epel/6/x86_64/epel-release-6-7.noarch.rpm - transfer failed
```

...

```
[default] Complete!
[default]  * Running install_centos_63_stable()
[default] Loaded plugins: fastestmirror, presto
[default]
Error getting repository data for epel-testing, repository not found
[default]  * Failed to run install_centos_63_stable()!!!
 * Removing the logging pipe /tmp/bootstrap-salt-minion.logpipe
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/tmp/bootstrap-salt-minion.sh -c /tmp/ stable
```

### CODE REVIEW

**Comment by akoumjian** [comment]
Thank you, forgot to do this!

**Comment by akoumjian** [comment]
I will put out a fix release gem soon.

**Comment by alecthomas** [comment]
Thanks for the prompt response!

**Comment by akoumjian** [comment]
Great name, by the way.
- Alec

**Comment by akoumjian** [comment]
Updated in rubygems as well.

**Comment by alecthomas** [comment]
Brilliant, thanks (and yes, agreed, our name is awesome :))

**Pull request merged**
