### PR TITLE
proper key inspection

### PR DESCRIPTION
**Pull request by whitmo**
Make the key inspection slightly more sophisticated.  This saves 10 second wait by only accepting pre-keys.

Currently the bootstrap starts both the minion and the master.  Unless we change the bootstrap to also handle key placement (probaby the right thing to do), the master will have a single unaccepted key when it starts.  I believe causes a 10 second hang judging by the logs.

This patch basically looks at all the keys we are uploading and all the keys that are in pre-salt for the master, and accepts those of the same name operating on the assumption they are the same.   This assumption is ok for development on a private network, but  opens a window for minion spoofing that would be unacceptable in a less controlled setting.

### CODE REVIEW

**Comment by whitmo** [comment]
Maybe the key should alway overwrite (even when accepting) to avoid a possible security hole.

**Comment by akoumjian** [comment]
> Unless we change the bootstrap to also handle key placement (probaby the right thing to do), the master will have a single unaccepted key when it starts

Let's change the seed_master to run before installing master, overwrite any existing keys, and not bother accepting keys after master has started. This is much more explicit and avoids all the messiness. Awesome work!

@raadad Please keep and eye on this and let's include it in the integrated PR when it's ready and tested. This is really critical as the current accept_keys method is broken.

**Comment by s0undt3ch** [comment]
Which keys are we really talking about here?

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Alec Koumjian" notifications@github.com
Para: "saltstack/salty-vagrant" salty-vagrant@noreply.github.com
Assunto: [salty-vagrant] proper key inspection (#74)
Data: qui, Abr 18, 2013 17:03
Unless we change the bootstrap to also handle key placement (probaby the right thing to do), the master will have a single unaccepted key when it starts 

Let's change the seed_master to run before installing master, overwrite any existing keys, and not bother accepting keys after master has started. This is much more explicit and avoids all the messiness. Awesome work! 

@raadad Please keep and eye on this and let's include it in the integrated PR when it's ready and tested. This is really critical as the current accept_keys method is broken. 

&mdash;

**Comment by akoumjian** [comment]
@s0undt3ch : This is for scenarios when users want to install a master on a vagrant VM, and connect other minions to it. Currently there is a way for users to run salt-key -A, but it's messy and potentially wastes time. New method (seed_master) lets the user explicitly declare and place a bunch of preseeded minion pub keys.

I am suggesting to @whitmo that we seed the master before even running bootstrap, and doing away with all the salt-key -A nonsense altogether.

**Comment by whitmo** [comment]
@akoumjian I need to look at the bootstrap (or just try it) and make sure the bootstrap doesn't blow away the pki directory (I know it creates it).

If the bootstrap has a `--seed-master-w-minions` flag that could load a directory of minion keys, it would be trivial to have the provisioner use that flag.   I would imagine this would be broadly useful for a variety of bootstrapping situations beyond salt-vagrant.

**Comment by akoumjian** [comment]
I'm open to both possibilities. Short of that we should also be able to copy them over after the master is installed. Not sure if it requires a restart or not.

**Comment by s0undt3ch** [comment]
Ah, pre seeded minion keys...
Yep, the script does not handle those...

**Comment by akoumjian** [comment]
@s0undt3ch : Are you open to it, or do you feel that it is outside bootstrap's scope?

**Comment by s0undt3ch** [comment]
I need to think if I see anything about it I dislike. So far, nothing :smiley: 
New ticket please?

**Comment by raadad** [comment]
@akoumjian  - No worries  , ill keep my eye on this issue and update once its done.

**Comment by whitmo** [comment]
will do

On Thu, Apr 18, 2013 at 5:17 PM, Pedro Algarvio notifications@github.comwrote:

> I need to think if I see anything about it I dislike. So far, nothing [image:
> :smiley:]
> New ticket please?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salty-vagrant/pull/74#issuecomment-16615247
> .

## 

<=>
david "whit" morriss

 "If you don't know where you are,
  you don't know anything at all"

  Dr. Edgar Spencer, Ph.D., 1995

**Comment by akoumjian** [comment]
@whitmo @s0undt3ch : If either of you are able to move forward on this today, it would be appreciated. I'm holding off on merging into vagrant until this last bit gets resolved.

**Comment by s0undt3ch** [comment]
Dam @akoumjian, just saw it now and I'm going home. Will be the first thing I do tomorrow!

**Comment by whitmo** [comment]
likewise, will set aside some time tomorrow morning for it.

On Mon, Apr 22, 2013 at 6:05 PM, Pedro Algarvio notifications@github.comwrote:

> Dam @akoumjian https://github.com/akoumjian, just saw it now and I'm
> going home. Will be the first thing I do tomorrow!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salty-vagrant/pull/74#issuecomment-16829556
> .

## 

<=>
david "whit" morriss

 "If you don't know where you are,
  you don't know anything at all"

  Dr. Edgar Spencer, Ph.D., 1995

**Comment by s0undt3ch** [comment]
The stable branch of the salt-boostrap script has been updated with this new feature.

**Comment by akoumjian** [comment]
Hey @whitmo, should I pick this up this weekend? I think it should be simple. Just update bootstrap, and use the new flag.

**Comment by whitmo** [comment]
Hey Alec, sorry for dropping off the radar (afk camping). if you didn't get
to it this weekend I can take a look today.

-w

On Fri, Apr 26, 2013 at 8:57 PM, Alec Koumjian notifications@github.comwrote:

> Hey @whitmo https://github.com/whitmo, should I pick this up this
> weekend? I think it should be simple. Just update bootstrap, and use the
> new flag.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salty-vagrant/pull/74#issuecomment-17108439
> .

## 

<=>
david "whit" morriss

 "If you don't know where you are,
  you don't know anything at all"

  Dr. Edgar Spencer, Ph.D., 1995

**Comment by akoumjian** [comment]
I did not, that would be great.

**Comment by whitmo** [comment]
Ok modified this PR to use the new bootstrap.  I ran into a small error with the bootstrap (unassigned variable) and fixed that here: https://github.com/saltstack/salt-bootstrap/pull/117 .  

Once fixed that and things seem to work with the "complete" example (I also updated the custom bootstrap).  

Provided the PR to salt-bootstrap looks ok to @s0undt3ch, this should be ready to merge.

**Comment by s0undt3ch** [comment]
I'm sad to say that my work on the bootstrap script regarding minion keys pre-seed is still buggy.
I'm glad to say that I'm fixing this.

**Comment by whitmo** [comment]
let me know if there is anything I can do to help.

On Wed, May 1, 2013 at 9:38 AM, Pedro Algarvio notifications@github.comwrote:

> I'm sad to say that my work on the bootstrap script regarding minion keys
> pre-seed is still buggy.
> I'm glad to say that I'm fixing this.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salty-vagrant/pull/74#issuecomment-17284485
> .

## 

<=>
david "whit" morriss

 "If you don't know where you are,
  you don't know anything at all"

  Dr. Edgar Spencer, Ph.D., 1995

**Comment by s0undt3ch** [comment]
There should be nothing much to do regarding salty-vagrant. I'm fixing things as I see them while also implementing pre-seeding on salt-cloud...

**Comment by akoumjian** [comment]
@s0undt3ch: Looks like I merged this hastily. :-p Should I test out preseeding now?

**Comment by s0undt3ch** [comment]
From the bootstrap dev branch, yes. Should be in stable in the next day or two. I'm just waiting for a comment to check if debian installs are ok using SaltStack's repo.

**Comment by s0undt3ch** [comment]
Oh, and its not your fault.

I made the changes and since I was focused on other things I assumed the correctness of my code without testing it ;)

But, when I was implementing pre-seeding in salt-cloud I found the bugs.

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Alec Koumjian" notifications@github.com
Para: "saltstack/salty-vagrant" salty-vagrant@noreply.github.com
Cc: "Pedro Algarvio" pedro@algarvio.me
Assunto: [salty-vagrant] proper key inspection (#74)
Data: sáb, Mai 4, 2013 00:18
@s0undt3ch: Looks like I merged this hastily. :-p Should I test out preseeding now? 

&mdash;

**Pull request merged**
