### PR TITLE
New bootstrap script

### PR DESCRIPTION
**Pull request by s0undt3ch**
Here's a new bootstrap approach. How about it?

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Do note that I'm still working on this. Right now adding git install support for ubuntu.

**Comment by s0undt3ch** [comment]
Err, can't use `echo -e` in ubuntu, though, in CentOS that's required... Maybe I should just loose the colors...

**Comment by s0undt3ch** [comment]
sh's echo implementation does not seem to support -e

Drop colours support?

**Comment by akoumjian** [comment]
I am currently reworking the bootstrap script to be as flexible as possible. I have been publishing my work in the rearrange branch. Short story is that we cannot really on bash or bash specific features.

**Comment by s0undt3ch** [comment]
I noticed you closed this pull request. I also looked at your rearrange branch.

Please don't get me wrong, and I also do not wish to step on your toes, but, have you looked at what I did on my script?

It will be supposed to install stable/daily(ubuntu)/git setup's.
Adding support for a distribution is as easy as following these steps(comment on script).

```
###############################################################################################
#
#   Distribution install functions
#
#   In order to install salt for a distribution you need to define:
#
#   To Install Dependencies, which is required, one of:
#       1. install_<distro>_<distro_version>_<install_type>_deps
#       2. install_<distro>_<distro_version>_deps
#       3. install_<distro>_<install_type>_deps
#       4. install_<distro>_deps
#
#
#   To install salt, which, of course, is required, one of:
#       1. install_<distro>_<distro_version>_<install_type>
#       1. install_<distro>_<install_type>
#
#   And optionally, define a post install function, one of:
#       1. install_<distro>_<distro_versions>_<install_type>_post
#       2. install_<distro>_<distro_versions>_post
#       3. install_<distro>_<install_type>_post
#       4. install_<distro>_post
#
###############################################################################################
```

A search for each of those functions, by that order, is done. First found, first executed.

The reason I may seem to be pushing this is because I'm working on vagrant testing support to salt using salty. The only "working" setup right now seems to be Ubuntu Precise, good, but we need to add CentoOS, Solaris and FreeBSD vagrant test support, at least, which is kind of holding back for salty.

**Comment by akoumjian** [comment]
@s0undt3ch, I do like the organization. You will see that in latest rearrange (which I just pushed, sorry) in triaging first and then delegating. I would be happy to incorporate that aspect of this pull request.

The first problem though is that this script requires bash to run which is a problem right from the get go. If we want arch or bsd support, we can't rely on it. Second is that I am not comfortable relying on wgeting this shtool script. I am open to including it in the scripts directory, however.

Last is that I am not convinced this logging will work in all the distributions we want to support. If we can get this running on vanilla arch, centos, and freebsd than I am happy to accept the pull request. Sorry for being hasty.

**Comment by s0undt3ch** [comment]
@akoumjian no need to apologise! I was stepping on your toes ;)

Regarding `wget`'ing the scripts, those scripts are GPL2. We would need to see if can actually include them, if we can, even better. Those are from a greater scripts package actually, "shtool".

Regarding the bash issue, yes, that was what I was working on by only running the script using `sh` and addressing the issues that popped up, and there are some issues validating the functions(are they defined or nor).

Regarding the logging stuff, it's about the same approach you have, we're both using named pipes to do the logging, just using a different approach, and the issue I had with it is that the colors that I'm using are also being logged(I should remove colors support).

I did encounter some other issues, related to `sh` vs `bash`, etc, when actually bootstrapping versus running the script on the running machine. Finding if a function is defined or not is way different while running `bash` vs `sh`, which was what I was addressing after submitting this pull request.

I think I just wanted to know if I was duplicating work, which seems that I was.

Well let me know if you want me to hold on(on whatever you're doin') or if I should pursue running this script using `sh` only.

**Comment by akoumjian** [comment]
Well you seem to know much better what you're doing and have the time, so I am happy to continue on what you've built.

Regarding logging, the method we are both using does not work in all the distros we want to support. That is one of the reasons I was not yet able to merge in the rearrange branch. If your version of using the pipes works in all the distros we've discussed, that's great. I was having issues.

Please continue working on this to be sh only and test it in debian/centos/arch and freebsd. 

As far as shtool being GPL2, that could be a problem. The eventual intention of this script is to include it in other salt projects such as salt-cloud. I don't like the idea of depending on an additional party's services to be up and running for all salt bootstrapping efforts everywhere to work correctly. At least now it is relegated to heavily tested and relied upon distribution specific services or github in case of develop mode.

Considering that it is really just a very finely grained version of what we already have, perhaps we should just evolve our own detection script and combined that with your function detection system. I do not believe we will need that level of finely grained detection, and that really we are looking at hitting just the half dozen to dozen most common distros/versions anyway.

**Comment by s0undt3ch** [comment]
@akoumjian script now runs with no errors on Debian, Ubuntu, CentOS 6.3 and Arch.

I'll now see if I include the system detection functions in our own script instead of `wget`'ting shtool.

**Comment by s0undt3ch** [comment]
Well, there are still errors in Arch because there are no install functions for it, @thatch45 care to "pitch" those in ;) ?

**Comment by akoumjian** [comment]
Fantastic, Pedro. Looking forward to it.

**Comment by akoumjian** [comment]
You can find them in salt-cloud (
https://github.com/saltstack/salt-cloud/tree/develop/saltcloud/deploy) or
you will find them in the rearrange branch.

**Comment by s0undt3ch** [comment]
By the way, anyone knows a link to a OpenBSD or FreeBSD vagrant `.box` which **has** virtualbox guest tools installed?

**Comment by thatch45** [comment]
What is the Arch status? The problem with Arch is that you generally need an up to date Arch system to install fresh software. Too bad my old VArch program is deprecated, otherwise it could be used to build vagrant images...

**Comment by s0undt3ch** [comment]
@akoumjian With this last commit, our system detection is working without any deps.

@thatch45 regarding the Arch status, adding the install functions should be pretty simple just by looking at the code comment. Still, after this work is finished, I'll be adding the several install functions needed to actually install salt on the various systems since I rely on those for my vagrant salt testing branch.

**Pull request merged**
