### PR TITLE
improve git install, and remove revision number from distribution version

### PR DESCRIPTION
**Pull request by ffa**
For git installs, the treeish may be specified with the "t" option. If it is
not specified, the master branch is the default treeish installed. Specifying
a treeish ensures a consistent environment which is detrimental to development.

The distribution version revision number
- is not a large enough change to effect installs
- needs the "." separate, which is currently removed, in the version number to
  be distinguished
- is not currently implemented for Sun and BSB installs

### CODE REVIEW

**Comment by ffa** [comment]
Crap, BSB should be BSD

**Comment by s0undt3ch** [comment]
@ff once @akoumjian updates the source with [my](https://github.com/saltstack/salty-vagrant/pull/25) pull request, please update your code so we can include your git installation changes into our script. Sorry for this extra trouble.

**Comment by akoumjian** [comment]
@ffa Please check against the latest develop. Instead of a separate option for git, the user simply uses one arg for install type (stable, daily, git) and then any additional args if necessary (such as git treeish).

However, if this is updated I am very happy to take the debian install functions.

**Comment by ffa** [comment]
I'm going to redo this and my other pull request to match your updates.

**Pull request closed without merging**
