### PR TITLE
relative require statement

### PR DESCRIPTION
**Pull request by ffa**
A relative require statement ensures the required file is included
correctly. For example, when the cwd is not in the lib directory.
So, vagrant-salt may be required directly from the Vagrantfile. This
is necessary in some situation, like when the "vagrant-salt" gem can't
be installed.

### CODE REVIEW

**Comment by akoumjian** [comment]
Although I am not a Ruby person, it appears that `require_relative` was not introduced until 1.9.2. Because we need this to be backwards compatible with host systems that are using older ruby versions, I don't believe I can merge in this change.

It appears as though you can still use `require '../lib/filename'` inside your Vagrantfile and get the same effect.

**Comment by ffa** [comment]
That doesn't seem to work. My setup leaves me with `require salty-vagrant/lib/vagrant-salt.rb` which fails.

How about I steal code from one of the two sources below which will solve the problem for <1.9.2?
https://github.com/appoxy/aws/blob/master/lib/awsbase/require_relative.rb
https://github.com/marcandre/backports/blob/master/lib/backports/tools.rb

Or, just change the line to `require File.expand_path("vagrant-salt/provisioner", File.dirname(__FILE__))`?

**Comment by akoumjian** [comment]
Your last suggestion seems like it could work. Can we make it conform to the style that the other Vagrant provisioners seem to use? https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/shell/plugin.rb

**Comment by ffa** [comment]
sure, what should I put in the "description" section? "Take a shower you dirty hippie", "A cannibals delight", "much like infrastructure management, salt tastes good on everyone", "as`salt`ing vagrants with infrastructure management", "A sweaty salty vagrant is the result of working hard to manage your infrastructure", ...

**Comment by akoumjian** [comment]
Have fun with the description, as long as it actually explains what it does. :+1:

**Comment by ffa** [comment]
I setup the new lib files, but the format is only for the unreleased version. And, until the new version of Vagrant is released, I'm unable to test (crashes). So, I'm pretty much stalled out. I can create a pull request if anyone else wants to try.

**Comment by akoumjian** [comment]
Going to close this as it no longer applies. But thanks for looking into it. :-)

**Pull request closed without merging**
