### PR TITLE
remove revision number from distribution version

### PR DESCRIPTION
**Pull request by ffa**
Remove the distribution version revision number becuase it
- is not a large enough change to effect installs
- needs the "." separator, which is currently removed, in the version number to
  be distinguished
- is not currently implemented for Sun and BSD installs

### CODE REVIEW

**Comment by akoumjian** [comment]
@s0undt3ch : Care to weigh in on this? I am ready to merge it in but I am not sure if affects anything unintentionally.

**Comment by s0undt3ch** [comment]
@ffa where, or better, which version was not detected in order for you to make the sed change? I'm asking because your previous pull request about this is what led me to finding that I was neglecting `/etc/lsb-release` and for that missing some matches.

So, what wasn't matched?

**Comment by ffa** [comment]
without this pull request, if "/etc/lsb-release" fails, the version format is "x.x[.x]" before the "." are removed. And, yes, the "[]" are not apart of the regex, but apart of the version number looked up. Furthermore, if the "[]" are removed, the outcome is "x.x.x" before the "." are removed. After the "." are removed, the number becomes "xxx" which is kind of ambiguous. For example, "10.0.4" and "10.04" both become "1004". So, I removed the revision number, "[.x]", entirely. But, if you prefer to keep the revision number, I recommend removing the "[]" at least.

Note: I'm using the naming scheme, "<major>.<minor>.<revision>".

**Comment by howardroark** [comment]
I assume that this causes me to experience this...  Should I be making new install functions for Debian 6.0.6?

BTW, I can't wait to start playing with salty vagrant! 
- System Information:
   CPU:          GenuineIntel x86_64
   OS Name:      Linux
   OS Version:   2.6.32-5-amd64
   Distribution: Debian 6.0[.6]
  - INFO: install_debian_60[6]_stable_deps not found....
  - INFO: install_debian_60[6]_deps not found....
  - INFO: install_debian_stable_deps not found....
  - INFO: install_debian_deps not found....
  - INFO: install_debian_60[6]_stable not found....
  - INFO: install_debian_stable not found....
  - INFO: install_debian_60[6]_stable_post not found....
  - INFO: install_debian_60[6]_post not found....
  - INFO: install_debian_stable_post not found....
  - INFO: install_debian_post not found....
  - ERROR: No dependencies installation function found. Exiting...

**Comment by akoumjian** [comment]
Makes sense to me. I don't believe we will need that kind of granularity.

**Pull request merged**
