### PR TITLE
Adding rudimentary support for RHEL/CentOS 6 bootstrap

### PR DESCRIPTION
**Pull request by benhosmer**
I'm wondering if these should be broken out into functions like they are in [salt-cloud](https://github.com/saltstack/salt-cloud/tree/develop/saltcloud/deploy) 

This might prevent duplicating effort.

### CODE REVIEW

**Comment by Gussy** [comment]
Nice work, this looks good to me :)

The problem with having separate scripts for bootstrapping is you need to then detect the guest OS either in Ruby, or transfer _all_ the scripts to the guest and then work out which one to target.

**Comment by benhosmer** [comment]
Good point, although we are essentially transferring all of the scripts now, they are just in one big file instead of many smaller ones.

I've wondered, as unpalatable as it is, if this functionality might be better included in the gem itself. I definitely don't have the Ruby knowledge to pull it off though.

Incidentally, what is the BASH equivalent of the -i used in the SH script? I can't find any reference for this. I assume the -s flag is the same as BASH and is verifying that the file isn't empty, but what is -i doing?

**Comment by akoumjian** [comment]
@benhosmer There are more differences than that. One is that the script includes the OS discovery and handles the triage by itself. It will be incredibly useful to have that all in one bootstrap file. Which `-i` are you talking about?

**Comment by benhosmer** [comment]
*Line 31 / scriptshttps://github.com/saltstack/salty-vagrant/tree/develop/scripts
 / bootstrap-salt-minion.sh *
OS=$(lsb_release -si)

On Wed, Sep 26, 2012 at 11:53 AM, Alec Koumjian notifications@github.comwrote:

> @benhosmer https://github.com/benhosmer There are more differences than
> that. One is that the script includes the OS discovery and handles the
> triage by itself. It will be incredibly useful to have that all in one
> bootstrap file. Which -i are you talking about?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salty-vagrant/pull/14#issuecomment-8894823.

## 

Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Comment by benhosmer** [comment]
Oh, and thanks for the merge too!

On Wed, Sep 26, 2012 at 8:48 PM, Ben Hosmer ben.hosmer@gmail.com wrote:

> *Line 31 / scriptshttps://github.com/saltstack/salty-vagrant/tree/develop/scripts
>  / bootstrap-salt-minion.sh *
> OS=$(lsb_release -si)
> 
> On Wed, Sep 26, 2012 at 11:53 AM, Alec Koumjian notifications@github.comwrote:
> 
> > @benhosmer https://github.com/benhosmer There are more differences
> > than that. One is that the script includes the OS discovery and handles the
> > triage by itself. It will be incredibly useful to have that all in one
> > bootstrap file. Which -i are you talking about?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salty-vagrant/pull/14#issuecomment-8894823.
> 
> ## 
> 
> Ben Hosmer
> 
> Brevard Tech - Brevard County Florida's Tech User Group
> http://www.brevardtech.org
> 
> Drupal Developer
> http://www.radarearth.com
> 
> 321.252.9581

## 

Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Comment by Gussy** [comment]
For lsb_release see here: http://manpages.ubuntu.com/manpages/precise/man1/lsb_release.1.html

Your confusion might be my fault. I vaguely remember implying that lsb_release was file in an earlier reply somewhere here, but it is in fact a command :)

**Comment by akoumjian** [comment]
You're welcome.

The `-i` and other flags are for the `lsb_release` binary which will be installed on systems with the `/etc/lsb-release` file.

[edit] Yes, what Gussy said.

**Comment by benhosmer** [comment]
Thanks to you both. I never knew it was a binary, I always just did cat
/etc/lsb-release

On Wed, Sep 26, 2012 at 8:53 PM, Alec Koumjian notifications@github.comwrote:

> You're welcome.
> 
> The -i and other flags are for the lsb_release binary which will be
> installed on systems with the /etc/lsb-release file.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salty-vagrant/pull/14#issuecomment-8915109.

## 

Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Pull request merged**
